apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
      type: DirectoryOrCreate
      path: /home/manojos/test


