name: build_n_deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read and increment version
        id: version
        run: |
          # Read the version from the VERSION file
          version=$(cat VERSION)
          echo "Current version: $version"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: manojthedonut/file-service:$version
          push: true

      # - name: Deploy to Kubernetes
      #   if: success() # Only run if previous steps succeeded
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
      #   run: |
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl rollout status deployment/your-deployment-name
